apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dtt-bot
  namespace: ponche-sb
spec:
  selector:
    matchLabels:
      project: dtt-bot
  template:
    metadata:
      labels:
        project: dtt-bot
    spec:
      containers:
        - name: dtt-bot-image
          image: poncheska/dtt-bot:latest
          env:
            - name: BOT_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: bot-config
                  key: bot_token
            - name: TT_LINK
              valueFrom:
                configMapKeyRef:
                  name: bot-config
                  key: tt_link
            - name: TT_SPAM
              valueFrom:
                configMapKeyRef:
                  name: bot-config
                  key: tt_spam
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /status
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /status
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 3